- name: Run backend application
  docker_container:
    name: simple-api
    image: aminesl/tp-devops-simple-api:latest
    networks:
      - name: mynetwork
    ports:
      - "8080:8080"
    env:
      DATABASE_HOST: "database"
      DATABASE_PASSWORD: "pwd"
