- name: Pull latest backend image
  community.docker.docker_image:
    name: aminesl/tp-devops-backend
    tag: latest
    source: pull
    force_source: true

- name: Run backend application
  community.docker.docker_container:
    name: simple-api
    image: aminesl/tp-devops-backend:latest
    networks:
      - name: mynetwork
    ports:
      - "8080:8080"
    env:
      DATABASE_HOST: "database"
      DATABASE_PASSWORD: "pwd"
