all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /Users/macbook/Documents/amine/ING2/EFREI/DevOps_MLOps/TP_Ansible/id_rsa
  children:
    prod:
      hosts:
        mohamed-amine.slimani.takima.cloud:
