- name: Launch PostgreSQL
  docker_container:
    name: database
    image: aminesl/tp-devops-database:latest
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    networks:
      - name: mynetwork
    state: started
