- name: Pull latest database image
  community.docker.docker_image:
    name: aminesl/tp-devops-database
    tag: latest
    source: pull
    force_source: true

- name: Launch PostgreSQL
  community.docker.docker_container:
    name: database
    image: aminesl/tp-devops-database:latest
    pull: true
    env:
      POSTGRES_USER: "{{ pg_user }}"
      POSTGRES_PASSWORD: "{{ pg_password }}"
      POSTGRES_DB: "{{ pg_database }}"
    networks:
      - name: mynetwork
    state: started
