- name: Pull latest proxy image
  community.docker.docker_image:
    name: aminesl/tp-devops-httpd
    tag: latest
    source: pull
    force_source: true

- name: Run proxy container
  community.docker.docker_container:
    name: my_proxy
    image: aminesl/tp-devops-httpd:latest
    pull: true
    ports:
      - "80:80"
    networks:
      - name: mynetwork
    env:
      USERNAME: aminesl
    state: started
