name: Déploiement Ansible

on:
  workflow_run:
    workflows: ["CD"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Configurer l'agent SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Installer Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Exécuter le playbook Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_DB: ${{ secrets.PG_DB }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          ansible-playbook -i ansible/inventories/setup.yml ansible/main.yml -u ${{ secrets.ANSIBLE_USER }}
